### ISSUE TITLE
fpm is quite outdated

### ISSUE THREAD

**Issue by indymx** [reef-pi/reef-pi#1793]
fpm is now at 1.14.1, yet we are still dependent on 1.6.1. This is causing issues building as there are problems with 1.6.1. (at least on ubuntu)

1.14.1 gives a clean build with no issues. 1.6.1 has given the following error for the past year or so. 

```
bundle exec fpm -t deb -s dir -a armhf -n reef-pi -v 5.2-6-g5f2d69da -m ranjib@linux.com --deb-systemd build/reef-pi.service -C dist  -p reef-pi-5.2-6-g5f2d69da.deb .
Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
Adding action files
Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag {:level=>:warn}
Traceback (most recent call last):
        9: from /usr/local/bin/fpm:23:in `<main>'
        8: from /usr/local/bin/fpm:23:in `load'
        7: from /var/lib/gems/2.7.0/gems/fpm-1.6.1/bin/fpm:8:in `<top (required)>'
        6: from /var/lib/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        5: from /var/lib/gems/2.7.0/gems/fpm-1.6.1/lib/fpm/command.rb:560:in `run'
        4: from /var/lib/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        3: from /var/lib/gems/2.7.0/gems/fpm-1.6.1/lib/fpm/command.rb:480:in `execute'
        2: from /var/lib/gems/2.7.0/gems/fpm-1.6.1/lib/fpm/package/deb.rb:443:in `output'
        1: from /var/lib/gems/2.7.0/gems/fpm-1.6.1/lib/fpm/package/deb.rb:443:in `tap'
/var/lib/gems/2.7.0/gems/fpm-1.6.1/lib/fpm/package/deb.rb:444:in `block in output': uninitialized constant FPM::Package::Deb::Zlib (NameError)
make: *** [Makefile:82: deb] Error 1

```

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1796
