### ISSUE TITLE
(bug) lighting module crashed in interval mode

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#960]
```
Dec 03 23:58:34 75gallon reef-pi[6735]: 2019/12/03 23:58:34 Reading temperature from device: 28-00000ab39d96
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 lighting subsystem: Setting Light: RearLight Channel: Blue Value: 98.95719270325979
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 lighting-subsystem: Setting PWM value: 98.95719270325979 at channel: 7
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 onTime 0 offTime 4052
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 Reading temperature from device: 28-00000ab3a23f
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 lighting subsystem: Setting Light: RearLight Channel: White Value: 0
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 lighting-subsystem: Setting PWM value: 0 at channel: 6
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 onTime 0 offTime 4096
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 lighting subsystem: Setting Light: FrontLight Channel: White Value: 0
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 lighting-subsystem: Setting PWM value: 0 at channel: 3
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 onTime 0 offTime 4096
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 lighting subsystem: Setting Light: FrontLight Channel: Blue Value: 98.95779903116652
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 lighting-subsystem: Setting PWM value: 98.95779903116652 at channel: 4
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 onTime 0 offTime 4052
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 Reading temperature from device: 28-00000a9a1050
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 temperature sub-system: sensor RightTemp value: 77.79
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 temperature sub-system: sensor AmbientTemp value: 69.13
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 Current value of 'RightTemp' is below minimum threshold. Executing up routine
Dec 03 23:58:35 75gallon reef-pi[6735]: 2019/12/03 23:58:35 Euipment: 4 On: true
Dec 03 23:58:36 75gallon reef-pi[6735]: 2019/12/03 23:58:36 ERROR: Failed to submit data to adafruit.io. User: Bigtrout Feed: righttemp-down Error: {"error":"not found - API documentation can be found at https://io.adafruit.com/api/docs
Dec 03 23:58:36 75gallon reef-pi[6735]: 2019/12/03 23:58:36 temperature sub-system: sensor LeftTemp value: 77.68
Dec 03 23:58:36 75gallon reef-pi[6735]: 2019/12/03 23:58:36 health check: Used memory: 7.66 Load5: 0.14
Dec 03 23:58:36 75gallon reef-pi[6735]: 2019/12/03 23:58:36 Current value of 'LeftTemp' is below minimum threshold. Executing up routine
Dec 03 23:58:36 75gallon reef-pi[6735]: 2019/12/03 23:58:36 Euipment: 3 On: true
Dec 03 23:58:36 75gallon reef-pi[6735]: 2019/12/03 23:58:36 ERROR: Failed to submit data to adafruit.io. User: Bigtrout Feed: lefttemp-down Error: {"error":"not found - API documentation can be found at https://io.adafruit.com/api/docs"
Dec 03 23:59:05 75gallon reef-pi[6735]: panic: runtime error: index out of range [12] with length 12
Dec 03 23:59:05 75gallon reef-pi[6735]: goroutine 43 [running]:
Dec 03 23:59:05 75gallon reef-pi[6735]: github.com/reef-pi/reef-pi/controller/pwm_profile.(*interval).Get(0x26ebd40, 0x4006d459, 0xbf71ed26, 0x784d8ecf, 0x4e80, 0xa20568, 0xa20568, 0x2709bd0)
Dec 03 23:59:05 75gallon reef-pi[6735]: /Users/ranjib/workspace/reef-pi/reef-pi/controller/pwm_profile/interval.go:27 +0x154
Dec 03 23:59:05 75gallon reef-pi[6735]: github.com/reef-pi/reef-pi/controller/modules/lighting.(*Channel).ValueAt(0x2455180, 0x4006d459, 0xbf71ed26, 0x784d8ecf, 0x4e80, 0xa20568, 0x4058bd4c, 0x0, 0x0, 0x40590000)
Dec 03 23:59:05 75gallon reef-pi[6735]: /Users/ranjib/workspace/reef-pi/reef-pi/controller/modules/lighting/channel.go:57 +0x58
Dec 03 23:59:05 75gallon reef-pi[6735]: github.com/reef-pi/reef-pi/controller/modules/lighting.(*Controller).syncLight(0x244b4d0, 0x28e2a60)
Dec 03 23:59:05 75gallon reef-pi[6735]: /Users/ranjib/workspace/reef-pi/reef-pi/controller/modules/lighting/light.go:134 +0x1f8
Dec 03 23:59:05 75gallon reef-pi[6735]: github.com/reef-pi/reef-pi/controller/modules/lighting.(*Controller).syncLights(0x244b4d0)
Dec 03 23:59:05 75gallon reef-pi[6735]: /Users/ranjib/workspace/reef-pi/reef-pi/controller/modules/lighting/controller.go:102 +0x58
Dec 03 23:59:05 75gallon reef-pi[6735]: github.com/reef-pi/reef-pi/controller/modules/lighting.(*Controller).StartCycle(0x244b4d0)
Dec 03 23:59:05 75gallon reef-pi[6735]: /Users/ranjib/workspace/reef-pi/reef-pi/controller/modules/lighting/controller.go:59 +0x4c
Dec 03 23:59:05 75gallon reef-pi[6735]: created by github.com/reef-pi/reef-pi/controller/modules/lighting.(*Controller).Start
Dec 03 23:59:05 75gallon reef-pi[6735]: /Users/ranjib/workspace/reef-pi/reef-pi/controller/modules/lighting/controller.go:48 +0x2c
Dec 03 23:59:05 75gallon systemd[1]: reef-pi.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 03 23:59:05 75gallon systemd[1]: reef-pi.service: Unit entered failed state.
Dec 03 23:59:05 75gallon systemd[1]: reef-pi.service: Failed with result 'exit-code'.
Dec 04 00:00:35 75gallon systemd[1]: reef-pi.service: Service hold-off time over, scheduling restart.
Dec 04 00:00:35 75gallon systemd[1]: fake-hwclock.service: Cannot add dependency job, ignoring: Unit fake-hwclock.service is masked.
Dec 04 00:00:35 75gallon systemd[1]: Stopped raspberry pi based reef tank controller.
Dec 04 00:00:35 75gallon systemd[1]: Started raspberry pi based reef tank controller.
Dec 04 00:00:35 75gallon reef-pi[7696]: 2019/12/04 00:00:35 driver-subsystem: registering driver id: rpi Name: Raspberry Pi
Dec 04 00:00:35 75gallon reef-pi[7696]: 2019/12/04 00:00:35 driver-subsystem: registering driver id: 1 Name: pHboard
Dec 04 00:00:35 75gallon reef-pi[7696]: 2019/12/04 00:00:35 driver-subsystem: registering driver id: 3 Name: PWM
Dec 04 00:00:35 75gallon reef-pi[7696]: 2019/12/04 00:00:35 Successfully started subsystem: system
Dec 04 00:00:35 75gallon reef-pi[7696]: 2019/12/04 00:00:35 INFO: equipment subsystem: Finished syncing all equipment
Dec 04 00:00:35 75gallon reef-pi[7696]: 2019/12/04 00:00:35 Successfully started subsystem: equipment
Dec 04 00:00:35 75gallon reef-pi[7696]: 2019/12/04 00:00:35 Successfully started subsystem: ato
Dec 04 00:00:37 75gallon reef-pi[7696]: 2019/12/04 00:00:37 Successfully started subsystem: lightings
Dec 04 00:00:37 75gallon reef-pi[7696]: 2019/12/04 00:00:37 lighting subsystem: Setting Light: RearLight Channel: White Value: 0
Dec 04 00:00:37 75gallon reef-pi[7696]: 2019/12/04 00:00:37 lighting-subsystem: Setting PWM value: 0 at channel: 6
Dec 04 00:00:37 75gallon reef-pi[7696]: 2019/12/04 00:00:37 onTime 0 offTime 4096
Dec 04 00:00:38 75gallon reef-pi[7696]: 2019/12/04 00:00:38 lighting subsystem: Setting Light: RearLight Channel: Blue Value: 98.51961305183093
Dec 04 00:00:38 75gallon reef-pi[7696]: 2019/12/04 00:00:38 lighting-subsystem: Setting PWM value: 98.51961305183093 at channel: 7
Dec 04 00:00:38 75gallon reef-pi[7696]: 2019/12/04 00:00:38 onTime 0 offTime 4034
Dec 04 00:00:38 75gallon reef-pi[7696]: 2019/12/04 00:00:38 lighting subsystem: Setting Light: FrontLight Channel: White Value: 0

Looks to be the lighting module causing the crash somehow
```

Reported by r2r member @bigtrout

**Comment by ranjib** [comment]
![l1](https://user-images.githubusercontent.com/316306/70123818-49bf5400-1628-11ea-8bd7-bb125ea46f0a.jpg)
![Screenshot_20191204-014214_Chrome](https://user-images.githubusercontent.com/316306/70123848-580d7000-1628-11ea-9835-1d097a088f04.jpg)
